### ISSUE TITLE
忽略更新按钮炸了

### ISSUE THREAD

**Issue by coderstory** [itsnows/android-upgrade#5]
android.database.sqlite.SQLiteException: 3 values for 2 columns (code 1 SQLITE_ERROR): , while compiling: INSERT OR REPLACE INTO upgrade_version(version,is_ignored)VALUES(?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1805)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1783)
        at com.itsnows.upgrade.model.UpgradeRepository.putUpgradeVersion(UpgradeRepository.java:86)
        at com.itsnows.upgrade.UpgradeDialog.ignoreUpgrade(UpgradeDialog.java:457)
        at com.itsnows.upgrade.UpgradeDialog.onClick(UpgradeDialog.java:495)
        at android.view.View.performClick(View.java:7270)
        at android.view.View.performClickInternal(View.java:7247)
        at android.view.View.access$3600(View.java:809)
        at android.view.View$PerformClick.run(View.java:27950)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:244)
        at android.app.ActivityThread.main(ActivityThread.java:7522)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1020)
2020-06-30 17:57:49.826 26353-28368/com.coderstory.flyme V/ANIMATION_AVOID: mIsSkipDoFrameBGEnabled = false
2020-06-30 17:57:49.827 26353-28368/com.coderstory.flyme V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
2020-06-30 17:57:51.823 26353-26353/com.coderstory.flyme I/oderstory.flym: System.exit called, status: 0
2020-06-30 17:57:51.823 26353-26353/com.coderstory.flyme I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.

**Comment by coderstory** [comment]
魅族17 android 10

**Comment by coderstory** [comment]
@Override
    public void putUpgradeVersion(UpgradeVersion version) {
        SQLiteDatabase db = helper.getWritableDatabase();
        String sql = "INSERT OR REPLACE INTO " +
                UpgradePersistenceContract.UpgradeVersionEntry.TABLE_NAME + "(" +
                UpgradePersistenceContract.UpgradeVersionEntry.COLUMN_NAME_VERSION + "," +
                UpgradePersistenceContract.UpgradeVersionEntry.COLUMN_NAME_IS_IGNORED + ")VALUES(?,?,?)";
        try {
            Object[] bindArgs = new Object[]{
                    version.getVersion(),
                    version.isIgnored()};
            db.execSQL(sql, bindArgs);
        } finally {
            if (db != null) {
                helper.close(db);
            }
        }
    }

明明是2个参数

**Comment by itsnows** [comment]
好的，感谢反馈。BUG已修复，最新版本：com.github.itsnows:android-upgrade:1.2.4
